export const projects = [
    {
        title: "Groop",
        tags: ['react', 'mongodb', 'nodejs', 'redis'],
        github: "https://github.com/amalik12/groop",
        image: "groop.gif",
        description: "A web based chat application, inspired by Slack and Discord. Users can create accounts, create chat rooms, and join other rooms with autogenerated links."
    },
    {
        title: "Draftnet",
        tags: ['django', 'tensorflow', 'angular'],
        github: "https://github.com/viking-sudo-rm/draftnet/",
        image: "draftnet.png",
        description: "A web app built with two friends that uses machine learning to suggest picks for players of the videogame Dota 2. I designed and built the front-end for the app, and contributed improvements to its neural network."
    },
    {
        title: "Dining Plus",
        tags: ['android', 'java', 'sqlite'],
        github: "https://github.com/amalik12/dining_plus",
        image: "diningplus.png",
        description: "For my senior thesis at Yale, I decided to create a proof-of-concept for a redesign of the school's dining app. I included several new features not in the original app, including sorting dining halls by distance, and favoriting menu items to receive notifications when they're being served."
    }
]

export const resume = [
    {
        title: "Software Engineer",
        org: ['Google', 'http://google.com'],
        image: 'google.png',
        dates: 'Feb 2020 - Present',
        location: "New York, NY",
        tags: ['java', 'javascript']
    },
    {
        title: "Software Engineer",
        org: ['Bloomberg', 'http://bloomberg.com'],
        image: 'bloomberg.png',
        dates: 'Sept 2018 - Feb 2020',
        location: "New York, NY",
        tags: ['c++', 'python'],
        description: "Developed several improvements to the backend services for the MARS function in the Bloomberg Terminal. Designed and implemented a new polling request model for the deal upload service, allowing clients to make large requests without triggering a timeout."
    },
    {
        title: "Solutions Engineer",
        org: ['Datadog', 'http://datadoghq.com'],
        image: 'datadog.png',
        dates: 'Jan 2018 - June 2018',
        location: "New York, NY",
        tags: ['python', 'javascript'],
        description: "Reproduced and debugged several issues with the product's dashboard and monitoring systems affecting a large number of users. Resolved issues for customers using the product through collaboration with engineering subteams and sales representatives."
    },
    {
        title: "Front End Engineering Intern",
        org: ['Business Insider', 'http://businessinsider.com'],
        image: 'bi.png',
        dates: 'June 2017 - Aug 2017',
        location: "New York, NY",
        tags: ['javascript', 'php', 'angularjs'],
        description: "Developed new features in the publication's content management system to support a new interview post type. Created a template for the website to display the new post type. Designed and implemented an audio player for article pages."
    },
    {
        title: "Undergraduate Learning Assistant",
        org: ['Yale University', 'http://yale.edu'],
        image: 'yale.png',
        dates: 'Sept 2016 - Dec 2016',
        location: "New Haven, CT",
        tags: ['c'],
        description: "Held weekly office hours to help students with their homework assignments. Graded homework and exams completed by students."
    },
    {
        title: "Research Intern",
        org: ['Yale Social Robotics Lab', 'http://scazlab.yale.edu'],
        image: 'socrob.png',
        dates: 'June 2016 - Aug 2016',
        location: "New Haven, CT",
        tags: ['python', 'opencv'],
        description: "Improved the accuracy of the project's computer vision system by building on its object tracking algorithm. Implemented a system to detect the depth of objects using two webcams."
    }
]